//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NonCSLA.WinFormUI.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/NonCSLA.WebRole")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IRandomNumbers")]
    public interface IRandomNumbers {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRandomNumbers/GetData", ReplyAction="http://tempuri.org/IRandomNumbers/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRandomNumbers/GetData", ReplyAction="http://tempuri.org/IRandomNumbers/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRandomNumbers/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IRandomNumbers/GetDataUsingDataContractResponse")]
        NonCSLA.WinFormUI.ServiceReference1.CompositeType GetDataUsingDataContract(NonCSLA.WinFormUI.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRandomNumbers/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IRandomNumbers/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<NonCSLA.WinFormUI.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(NonCSLA.WinFormUI.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRandomNumbers/GetNumber", ReplyAction="http://tempuri.org/IRandomNumbers/GetNumberResponse")]
        string GetNumber();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRandomNumbers/GetNumber", ReplyAction="http://tempuri.org/IRandomNumbers/GetNumberResponse")]
        System.Threading.Tasks.Task<string> GetNumberAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRandomNumbersChannel : NonCSLA.WinFormUI.ServiceReference1.IRandomNumbers, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RandomNumbersClient : System.ServiceModel.ClientBase<NonCSLA.WinFormUI.ServiceReference1.IRandomNumbers>, NonCSLA.WinFormUI.ServiceReference1.IRandomNumbers {
        
        public RandomNumbersClient() {
        }
        
        public RandomNumbersClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RandomNumbersClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RandomNumbersClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RandomNumbersClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public NonCSLA.WinFormUI.ServiceReference1.CompositeType GetDataUsingDataContract(NonCSLA.WinFormUI.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<NonCSLA.WinFormUI.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(NonCSLA.WinFormUI.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public string GetNumber() {
            return base.Channel.GetNumber();
        }
        
        public System.Threading.Tasks.Task<string> GetNumberAsync() {
            return base.Channel.GetNumberAsync();
        }
    }
}
